#
# Copyright (c) 2013-2018 by Pawel Tomulik
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE


Import(['env'])

import os
import sys

def running_in_virtualenv():
    return (hasattr(sys, 'real_prefix') or
            (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix))

def is_scons_dir(path):
    return os.path.isfile(os.path.join(path, 'SCons', '__init__.py'))

def scons_path():
    return [x for x in sys.path if is_scons_dir(x)]

epydoc = env.Detect(['epydoc'])
if epydoc:
    path = ':'.join([str(env.Dir('#/sconstool'))] + scons_path())
    epydocflags = '-v --html --css grayscale --inheritance listed'
    epydoccom = 'PYTHONPATH=%s %s -o $TARGET.dir %s %s' \
            % (path, epydoc, epydocflags, 'texas')
    target = ['index.html']
    source = [env.Glob('#/*.py')]
    api_doc = env.Command(target, source, epydoccom)
    env.AlwaysBuild(env.Alias('api-doc', api_doc))
    env.Ignore('.', target)

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
